name: Deploy to GitHub Pages

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages.yml@main
    with:
      publish_dir: build
